# Generated by Django 4.1.10 on 2023-09-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_foundingdocumentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOUTResultPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='meta description')),
                ('title', models.CharField(max_length=250, verbose_name='h1-заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('text_top', models.TextField(blank=True, verbose_name='текст')),
                ('text_bottom', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'результаты проведения СОУТ',
                'verbose_name_plural': 'результаты проведения СОУТ',
            },
        ),
    ]
