# Generated by Django 4.1.10 on 2023-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015)], default=2023, verbose_name='год'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015)], default=2023, verbose_name='год'),
        ),
    ]
