# Generated by Django 4.1.10 on 2023-09-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationfund',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='decisionmeeting',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='federallaw',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='foundingdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='localregulation',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='regulatorylegal',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='soutresult',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='technicalregulation',
            name='file_size',
        ),
    ]
