# Generated by Django 4.1.10 on 2023-09-12 13:59

import common.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_inspection_year_alter_reporting_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOUTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать?')),
                ('name', models.TextField(verbose_name='название')),
                ('file_path', models.FileField(max_length=140, upload_to=common.helpers.get_doc_name_file_path, validators=[django.core.validators.FileExtensionValidator(('doc', 'docx', 'xls', 'xlsx', 'rtf', 'pdf', 'zip', '7z', 'rar'))], verbose_name='путь к файлу')),
                ('file_size', models.CharField(blank=True, max_length=30, verbose_name='размер файла')),
            ],
            options={
                'verbose_name': 'результаты проведения СОУТ',
                'verbose_name_plural': 'результаты проведения СОУТ',
            },
        ),
    ]
