# Generated by Django 4.1.10 on 2023-09-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_compensationfund_file_size_decisionmeeting_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationfund',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='decisionmeeting',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='federallaw',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='foundingdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='localregulation',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='regulatorylegal',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='soutresult',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='technicalregulation',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
    ]
