# Generated by Django 4.1.10 on 2023-09-07 10:25

import common.helpers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('path', models.FileField(max_length=250, upload_to=common.helpers.get_file_path, validators=[django.core.validators.FileExtensionValidator(('doc', 'docx', 'xls', 'xlsx', 'rtf', 'pdf', 'zip', '7z', 'rar'))], verbose_name='Путь к документу')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
    ]
