# Generated by Django 4.1.10 on 2023-09-15 03:48

import common.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=250, upload_to=common.helpers.get_file_path, validators=[django.core.validators.FileExtensionValidator(('doc', 'docx', 'xls', 'xlsx', 'rtf', 'pdf', 'zip', '7z', 'rar'))], verbose_name='путь к документу'),
        ),
    ]
