# Generated by Django 4.1.10 on 2023-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='название'),
            preserve_default=False,
        ),
    ]
