# Generated by Django 4.1.10 on 2023-09-13 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'место нахождения',
                'verbose_name_plural': 'место нахождения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrgForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=10, verbose_name='сокращенное название')),
                ('fullname', models.CharField(max_length=100, verbose_name='полное название')),
            ],
            options={
                'verbose_name': 'форма организации',
                'verbose_name_plural': 'формы организации',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать?')),
                ('date', models.DateField(verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-date',),
                'unique_together': {('date', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать?')),
                ('reg_num', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='рег. №')),
                ('reg_date', models.DateField(verbose_name='дата регистрации')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[0-9+]', 'Можно вводить только цифры.')], verbose_name='ИНН')),
                ('ogrn', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator('^[0-9+]', 'Можно вводить только цифры.')], verbose_name='ОГРН')),
                ('company_fullname', models.CharField(blank=True, db_index=True, help_text='например: "Самая Лучшая Компания"', max_length=250, verbose_name='полное название компании')),
                ('company_shortname', models.CharField(blank=True, db_index=True, help_text='например: "СЛК"', max_length=250, verbose_name='сокращенное название компании')),
                ('lastname', models.CharField(db_index=True, max_length=100, verbose_name='фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='отчество')),
                ('excluded', models.BooleanField(db_index=True, default=False, verbose_name='исключен из ассоциации?')),
                ('excluded_date', models.DateField(blank=True, null=True, verbose_name='дата исключения')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.location', verbose_name='место нахождения')),
                ('org_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.orgform', verbose_name='форма организации')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.position', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'член ассоциации',
                'verbose_name_plural': 'члены ассоциации',
                'ordering': ('reg_num',),
            },
        ),
    ]
