# Generated by Django 4.1.10 on 2023-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company_fullname',
            field=models.CharField(blank=True, db_index=True, help_text='например: "Самая Лучшая Компания"', max_length=250, verbose_name='полное название компании'),
        ),
        migrations.AlterField(
            model_name='member',
            name='company_shortname',
            field=models.CharField(blank=True, db_index=True, help_text='например: "СЛК"', max_length=250, verbose_name='сокращенное название компании'),
        ),
    ]
