# Generated by Django 4.1.10 on 2023-09-06 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_member_company_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[0-9+]', 'Можно вводить только цифры.')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ogrn',
            field=models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator('^[0-9+]', 'Можно вводить только цифры.')], verbose_name='ОГРН'),
        ),
    ]
